# Generated by Django 3.2.8 on 2023-08-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hobby',
            name='summary',
            field=models.CharField(max_length=20),
        ),
    ]
